### ISSUE TITLE
Getting quicker imagery

### ISSUE THREAD

**Issue by IkonoDim** [cnadler86/micropython-camera-API#14]
Is there any way of taking pictures quicker? E.g. for video recording? I don't need much fps. Like 5-10 would be fine. However one frame every 3 seconds in svga is simply not enough.

**Comment by cnadler86** [comment]
What is your configuration, especially fb_count, pixel_format and grab_mode?

Have you looked at the benchmark? For jpeg and fb_count =2 you can achieve around 25fps on a S3 Chip

**Comment by IkonoDim** [comment]
Alright, just tested it on another chip and it didn't have any kind of delay. Seems like a malfunctioning 2.4 Ghz antenna
