### ISSUE TITLE
Unknown error 0xffffffff occurring when taking a picture

### ISSUE THREAD

**Issue by IkonoDim** [cnadler86/micropython-camera-API#15]
Hi! Whenever I try taking a picture with any resolution over QVGA it fails with an unknown RuntimeError.

I am using the official Freenove ESP32-S3-WROOM CAM board.

Code snippet:
```py
from camera import Camera, GrabMode, PixelFormat, FrameSize, GainCeiling

cam = Camera(pixel_format=PixelFormat.GRAYSCALE,
             frame_size=FrameSize.SVGA,
             fb_count=2,
             grab_mode=GrabMode.LATEST)

pic = cam.capture()
```

Full error:
```
Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
RuntimeError: Unknown error 0xffffffff
```

**Comment by cnadler86** [comment]
Hi. Not all compilations of settings deliver pics. 

Probably it is to much stress for the Chip. Try using fb_count =1 or 10MHz, or use jpeg.

**Comment by cnadler86** [comment]
You can also configure your camera for jpeg and pass RGB565 as argument for capture. Then the image will be captured in jpeg but converted to RGB565. 
See the readme to see how to do that.

**Comment by IkonoDim** [comment]
> **cnadler86**
> Hi. Not all compilations of settings deliver pics.
> 
> Probably it is to much stress for the Chip. Try using fb_count =1 or 10MHz, or use jpeg.

Thank you very much. It is working after I lowered the fb_count.
